apiVersion: v1
entries:
  ks-gateway-autodns-server:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-02-02T08:34:43.242463683Z"
    description: A Helm chart for KubeSphere Gateway AutoDNS Server
    digest: 5f0e4d82674677bbf789b544f3260742b2c23f0d6b8ab143802c575fa5c39022
    keywords:
    - kubesphere
    - gateway
    - autodns
    - dns
    - apisix
    maintainers:
    - name: veater
    name: ks-gateway-autodns-server
    type: application
    urls:
    - https://annopick.github.io/ks-gateway-autodns/charts/ks-gateway-autodns-server-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-02T08:34:43.241780736Z"
