apiVersion: v1
entries:
  ks-gateway-autodns-server:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-02-02T11:42:27.204031379Z"
    description: A Helm chart for KubeSphere Gateway AutoDNS Server
    digest: 96177ee8a10a9c3b2c7818c0d52a30cf3100dd9d27db483fcd26bf18a68a1f91
    keywords:
    - kubesphere
    - gateway
    - autodns
    - dns
    - apisix
    maintainers:
    - name: veater
    name: ks-gateway-autodns-server
    type: application
    urls:
    - https://annopick.github.io/ks-gateway-autodns/charts/ks-gateway-autodns-server-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-02T11:42:27.203383808Z"
